# Generated by Django 6.0.7 on 2026-07-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField()),
                ('tecnologias', models.JSONField(default=list)),
                ('link', models.URLField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
